# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

source 'https://cdn.cocoapods.org/'
source 'https://gitee.com/devjackcat/JCS_PodSpecs.git'
#source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target '__ProjectName__' do
 
end
